name = "Lattice"
uuid = "fe356c0f-7f20-4673-b63f-34bd49dc17a0"
authors = ["Arun George Saji <arungeorgesaji@gmail.com>"]
version = "1.0.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[compat]
FileIO = "1.17.1"
Images = "0.26.2"
