name = "Lattice"
uuid = "fe356c0f-7f20-4673-b63f-34bd49dc17a0"
authors = ["Arun George Saji <arungeorgesaji@gmail.com>"]
version = "1.0.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
FileIO = "1.17.1"
Images = "0.26.2"
JSON3 = "1.14.3"
Plots = "1.41.1"
Serialization = "1.11.0"
